### ISSUE TITLE
cid Undef cannot be marshalled

### ISSUE THREAD

**Issue by ickby** [ipfs/go-cid#129]
Cid implements multiple go encoding interfaces, including golangs "encoding.BinaryUnmarshaler". For this it uses the function "CidFromBytes" via "Cast". However, this function cannot handle empty bytes. As the default value of a undefined cid, CidUndef, is represented via empty string/byte sequence, a problem arises. One can marshal all cids, except cid Undef, which results in an error.  Imho this should be possible, as CidUndef is a valid part of the implementation. 

To reproduce the problem:
`

          func main() {
	          gob.Register(new(cid.Cid))
          
	          c1 := cid.Undef
	          var network bytes.Buffer
	          enc := gob.NewEncoder(&network)
	          err := enc.Encode(c1)
	          if err != nil {
		          fmt.Printf("encode error: %v", err)
	          }
          
	          dec := gob.NewDecoder(&network)
	          var c2 cid.Cid
	          err = dec.Decode(&c2)
	          if err != nil {
		          fmt.Printf("decode error: %v\n", err)
	          }
          }
`
This results in "decode error: varints malformed, could not reach the end"

**Comment by Stebalien** [comment]
"Undef" is really just the "nil" type for CIDs, and it's _not_ a valid CID. We refuse to unmarshal zero-length json/text CIDs as well.

Unfortunately, with "UnmarshalBinary", there is no real "null".

**Comment by ickby** [comment]
ok, if it's a deliberate decision I work around it.
