### ISSUE TITLE
Allow CID to reference public keys (possibly make it extensible)

### ISSUE THREAD

**Issue by mildred** [ipfs/go-cid#15]
See message on IRC: https://botbot.me/freenode/ipfs/msg/78509267/

Currently, when looking up [public keys](https://github.com/libp2p/go-libp2p-routing/blob/110040fbb98fbab83142c6bc7078e463d50743d8/routing.go#L91-L105), the [generic value store interface](https://github.com/libp2p/go-libp2p-routing/blob/110040fbb98fbab83142c6bc7078e463d50743d8/routing.go#L19-L25) of the DHT is used.

This has the effect that when, for example looking up a public key (but this is the same for naming), the DHT is queried twice. Once for [the correspondance between the public key fingerprint to know the block id](https://github.com/libp2p/go-libp2p-routing/blob/110040fbb98fbab83142c6bc7078e463d50743d8/routing.go#L96-L100) and once more to [get the list of peers that can provide the block with the id we just got](https://github.com/libp2p/go-libp2p-routing/blob/110040fbb98fbab83142c6bc7078e463d50743d8/routing.go#L102-L103).

Instead, the key could be directly lookup up using the [content lookup interface](https://github.com/libp2p/go-libp2p-routing/blob/110040fbb98fbab83142c6bc7078e463d50743d8/routing.go#L17-L25) of the DHT. This interface takes a CID and respond with a list of peers directly. This is exactly what we need.

I suggest that we add an encoding in the CID to represent a public key from the key hash to avoid the two phase lookup. This is what this ticket is for.

I also suggest that instead of taking a pointer to a CID value, the routing interface references an interface type instead, that could be implemented differently. This is to be tracked in [libp2p/go-libp2p-routing](https://github.com/libp2p/go-libp2p-routing).

_Don't hesitate to chat with me over IRC, realtime makes it easier to remove ambiguities_

**Comment by whyrusleeping** [comment]
@mildred agreed on wanting a CID codec to easily reference keys. We want to use ipld to do this, and call the format multikey.

However, we could address the problem you bring up without that. If peers added their public keys into the blockstore then you could move them around with bitswap, and peers could fetch public keys that way instead of requiring a dht query

**Comment by lidel** [comment]
FYSA we now have `libp2p-key` multicodec, it is used for representing PeerIDs as CIDs: https://github.com/multiformats/multicodec/issues/130
