### ISSUE TITLE
consider moving _rsrch/cidiface to internal

### ISSUE THREAD

**Issue by MichaelMure** [ipfs/go-cid#168]
As I understand, `_rsrch/cidiface` is an engineering experiment package to explore the right form for a CID. As such, it's not meant to be actually used, and could result in conflict if used. There is definitely value in that package, if only to document design choices.

My (admittedly little) issue is that my IDE keeps suggesting me to import that package, and sometimes does. It would be way less confusing for everyone if `_rsrch/cidiface` would be moved into `internal/_rsrch/cidiface` or something similar.

**Comment by gammazero** [comment]
Sounds like a good idea. PR would be great. Either move it to internal or remove it if no longer needed.

**Comment by MichaelMure** [comment]
@gammazero here is the PR: https://github.com/ipfs/go-cid/pull/169
