### ISSUE TITLE
It would be nice to add Less()

### ISSUE THREAD

**Issue by aboodman** [ipfs/go-cid#46]
It's common to want to sort `Cid`, which requires an implementation of `Less()`. This can be done more efficiently inside `Cid` than outside because it won't require allocation if done inside (can directly access member fields which aren't exposed outside the package).

**Comment by dignifiedquire** [comment]
@Stebalien any thoughts here?

**Comment by dignifiedquire** [comment]
> (today?)

:tada:

**Comment by kevina** [comment]
We are now using string-backed CIDs.
