### ISSUE TITLE
Extract non-core functionaly into new package

### ISSUE THREAD

**Issue by kevina** [ipfs/go-cid#68]
`go-cid` is used by any package that does anything IPFS or IPLD related.  we should probably move non-core functionally into a new package to avoid having to update so many packages when non-core functionality changes.

Code in the following packages should likely be moved:
  * `set.go` and tests
  * `format.go` and tests
  * Everything in `cid-fmt/`.

**Comment by kevina** [comment]
@Stebalien you didn't want to extract set.go, what parts did you want to extract to `go-cidutil`?  Do you want to move `StreamingSet`?

**Comment by Stebalien** [comment]
For now, let's leave `set.go` (well, the `Set` structure *in* `set.go`). However, feel free to move `StreamingSet`. Given that it's a "new" feature, feel free to "move" it by recommitting it to the new repo (just make sure to set the commit author to magik6k).

**Comment by Stebalien** [comment]
I would move `format.go` and `cid-fmt` (and the `Identity` cid builder).

**Comment by kevina** [comment]
Okay.  Just how many packages use `cid.Set`?

The Identity will come imminently after the extraction and I will make a p.r. for it.

**Comment by Stebalien** [comment]
ipfs, bitswap, filecoin. I'm not really worried about breaking *our* code, I just don't want to mass-break other people's code (yet).
