### ISSUE TITLE
Qm hash identifiers duplicated within the IPFS ecosystem

### ISSUE THREAD

**Issue by lsji07** [ipfs/go-cid#87]
Hi,

My issue is in connection with adding IPFS metadata to another chain.

In my case Ravencoin. We use the CID to link to the immutable file (record, pdf, etc) of the digital token on the ravencoin chain.

We expect the Qm (46 character hash starting with Qm) hash to be immutable. 

However we have found that the IPFS node **peer ID** (used in IPNS) is **also** a Qm hash with 46 characters. That hash is mutable or changes to whatever that peer is publishing.

Two questions - 
Is there a way of identifying which Qm hash is immutable?

I have seen PR #86 which seems to indicate that the Peer ID's will be changing from the Qm 46 character hash. Is that correct? If so my issue will be fixed anyway...i live in hope...

**Comment by Stebalien** [comment]
We'd be happy to answer your question on [discuss.ipfs.io](https://discuss.ipfs.io).
